ALTER TABLE candidatos
ADD COLUMN IF NOT EXISTS experiencia_total_anos INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS fuente VARCHAR(100) DEFAULT 'Portal',
ADD COLUMN IF NOT EXISTS etapa VARCHAR(50) DEFAULT 'Nuevo',
ADD COLUMN IF NOT EXISTS estado VARCHAR(50) DEFAULT 'Activo';
